name: sng
description: Startup Name Generator.

version: 0.1.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter_launcher_icons: ^0.6.1
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
   image_path: "icon/icon.png"
   android: true
   ios: true